<?php

/** @file
 * Maim file for custom hooks and functions.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\node\Entity\NodeType;
use Drupal\node\NodeInterface;

/**
 * Implements gook_theme().
 */
function dlog_theme($eisting, $type, $theme, $path){
  return [
    'dlog_previous_next' => [
      'variables' => [
        'entity' => NULL,
      ],
      'file' => 'dlog.theme.inc',
    ]
  ];
}

/**
 * Implements dlog_entity_extra_field_info().
 */
function dlog_entity_extra_field_info() {
  $extra = [];

  foreach (NodeType::loadMultiple() as $bundle) {
    $extra['node'][$bundle->id()]['display']['previous_next'] = [
      'label' => t('Buttons to previous and next entity'),
      'weight' => 100,
      'visible' => FALSE,
    ];

    return $extra;
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function dlog_node_view(array &$build, NodeInterface $node, EntityViewDisplayInterface $display, $view_mode){
  if ($display->getComponent('previous_next')){
    $build['previous_next'] = [
      '#theme' => 'dlog_previous_next',
      '#entity' => $node,
    ];
  }
}
