<?php

/**
 * @file
 * Main file for custom hooks and functions.
 */

/**
 * Implements hook_theme().
 */
function dlog_hero_theme($existing, $type, $theme, $path) {
  return [
    'dlog_hero' => [
      'variables' => [
        'title' => NULL,
        'subtitle' => NULL,
        'image' => NULL,
        'video' => [],
      ],
      'file' => 'dlog_hero.theme.inc',
      'pattern' => 'dlog_hero__',
    ],
  ];
}

/**
 * Implements dlog_hero_theme_suggestions_HOOK for dlog-hero.html.twig.
 */
function dlog_hero_theme_suggestions_HOOK(array $variables) {
  $suggestions = [];

  if (!empty($variables['image'])) {
    $suggestions[] = 'dlo_hero__image';
  }

  if (!empty($variables['video']) && !empty($variables['image'])) {
    $suggestions[] = 'dlo_hero__video';
  }


  return $suggestions;
}
